site_name: Encrypted Wiki

theme:
  name: material
  palette:
    scheme: slate
    primary: black
  features:
    - content.code.copy # ميزة نسخ الكود

# 🛠️ التصحيح هنا: أضفنا 'attr_list' لتشغيل خاصية اسم اللغة (Title)
markdown_extensions:
  - attr_list
  - pymdownx.superfences

extra_css:
  - css/extra.css

nav:
  - Home: index.md
